### ISSUE TITLE
filetime에 관한 기반기술조사

### ISSUE THREAD

**Issue by wns1119** [wns1119/project2#6]
기반기술을 조사해야합니다.

**Comment by pjh6818** [comment]
### #include <time.h>
### struct tm * localtime(const time_t* timep);
===========================================

- localtime(): time_t값을 활용할 수 있게 가공시켜주는 함수

- const time_t* timep : time_t형 변수를 가리키는 포인터

- struct tm* localtime : 시간 정보가 들어가는 구조체 포인터
_**struct tm {
int tm_sec; /* seconds */
int tm_min; /* minutes */
int tm_hour; /* hours */
int tm_mday; /* day of the month */
int tm_mon; /* month */
int tm_year; /* year */
int tm_wday; /* day of the week */
int tm_yday; /* day in the year */
int tm_isdst; /* daylight saving time */
};**_

-  month의 경우 0부터 시작함(1월이 0으로 나타남)

**Comment by wns1119** [comment]
정보 조사가 끝났습니다. 이슈를 close합니다.
