### ISSUE TITLE
filetime의 코드 구현

### ISSUE THREAD

**Issue by wns1119** [wns1119/project2#7]
filetime에 관한 코드를 구현해야합니다.

**Comment by wns1119** [comment]
void filetime1(void)

{
	time1 = localtime(&stat1.st_mtime);

}



void filetime2(void)

{
	time2 = localtime(&stat2.st_mtime);

}

제가 추가한 코드는 다음과 같습니다.

**Comment by pjh6818** [comment]
#10 comment 확인해주세요!!

**Comment by wns1119** [comment]
코멘트 확인하였습니다. merge되었으므로 issue를 close합니다.
