### ISSUE TITLE
filetime 코드 리뷰

### ISSUE THREAD

**Issue by wns1119** [wns1119/project2#8]
작성한 filetime코드에 관해서 리뷰해주십시오.

**Comment by kty9418** [comment]
#10 의 comment 내용 대로 코드 수정 부탁드립니다.

**Comment by wns1119** [comment]
수정 완료하였습니다. 추가적인 지적 사항이 없다면 #10 가 merge된 이후 issue를 종료해도 될 것 같습니다.
